version: "3"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.dev

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: