version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./app/.env.dev
    depends_on:
      - redis
      - mongodb
    volumes:
      - ./app:/app

  recommender:
    build:
      context: .
      dockerfile: ./recommender/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./recommender/.env.dev
    depends_on:
      - redis
      - mongodb
    volumes:
      - ./recommender:/recommender

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456Aa
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
