version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456Aa
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    restart: always
    depends_on:
      - redis
      - mongodb

volumes:
  mongo_data: